**1. Importer et inqstallation du Package**

In [1]:
#pip install pandas
import pandas as pd

**2. Création du Data frame**

**2.1 Création à partir d'un dictionnaire**

In [8]:
#Création d'un dictionnaire
etudiant = {"Nom" :["Mendong","Zibi","Ekounou","Bastos"],
            "Prenom":["Chloe","Loic","Helene","Nathan"],
            "Notes":[19,18,15,13]}
etudiant

{'Nom': ['Mendong', 'Zibi', 'Ekounou', 'Bastos'],
 'Prenom': ['Chloe', 'Loic', 'Helene', 'Nathan'],
 'Notes': [19, 18, 15, 13]}

In [11]:
#Tansformer le dictionnaire en dataframe
df_etudiant = pd.DataFrame(etudiant)
df_etudiant

       Nom  Prenom  Notes
0  Mendong   Chloe     19
1     Zibi    Loic     18
2  Ekounou  Helene     15
3   Bastos  Nathan     13

**2.2 Création à partir d'un fichier csv/excel**

In [15]:
#Importation du fichier csv
df=pd.read_csv("credit_risk_dataset.csv", sep=";")
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

In [20]:
#Importation du fichier excel
df=pd.read_excel("credit_dataset_excel.xlsx")
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

**2.3 Afficher un dataframe et afficher le type de données et description de colonne**

In [23]:
#Afficher les 5 premier éléments
df.head(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4

In [24]:
#Afficher les 5 derniers éléments
df.tail(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

In [25]:
#Voir la liste des colonnes du dataframe
df.columns

Index(['Id_personne', 'Age', 'Nom', 'Prenom', 'Revenu', 'Type de domicile',
       'Travail', 'Grade du pret', 'Montant du prêt', 'Taux_interet',
       'Statut_du_pret', 'Taux_endettement', 'Défaut',
       'Nombre de credit historique'],
      dtype='str')

In [27]:
#Voir le type de données de ma base de données
df.dtypes

Id_personne                      int64
Age                              int64
Nom                                str
Prenom                             str
Revenu                           int64
Type de domicile                   str
Travail                            str
Grade du pret                      str
Montant du prêt                  int64
Taux_interet                   float64
Statut_du_pret                   int64
Taux_endettement               float64
Défaut                             str
Nombre de credit historique      int64
dtype: object

In [28]:
#Voir la dimension de notre tableau
df.shape

(20, 14)

**3. Lecture des tableaux pandas**

**3.1 Sélectionner des colonnes**

In [30]:
#Si la variable n'a pas d'espace
df.Id_personne.head(5)

0    1
1    2
2    3
3    4
4    5
Name: Id_personne, dtype: int64

In [36]:
#Si la variable à des caractères spéciaux
df["Type de domicile"].head(6)

0       Locataire
1    Propriétaire
2       Locataire
3            Pret
4            Pret
5       Locataire
Name: Type de domicile, dtype: str

In [42]:
#Sélectionner plusieurs colonnes
new_df = df[["Type de domicile", "Nom"]]
new_df.head(4)

  Type de domicile     Nom
0        Locataire   Akono
1     Propriétaire    Akwa
2        Locataire  Arnaud
3             Pret     Awa

In [45]:
#Connaitre les valeurs uniques d'une liste
df["Type de domicile"].unique()

<StringArray>
['Locataire', 'Propriétaire', 'Pret']
Length: 3, dtype: str

**3.2 Selectionner des lignes**

In [47]:
#Sélectionner des lignes qui respectent une condition unique
new_cdi = df[df["Travail"]=="CDI"]
new_cdi.head(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3

In [50]:
#Selectionner des lignes avec plusieurs conditions
new_pret = df[(df["Travail"]=="CDI") & (df["Grade du pret"]=="D")]
new_pret.head(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3

**3.3 Indexation avec iloc(index location)**

In [54]:
#Sélection de la première ligne
df.iloc[0]

Id_personne                            1
Age                                   40
Nom                                Akono
Prenom                            Nathan
Revenu                             59000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          D
Montant du prêt                    35000
Taux_interet                       16.02
Statut_du_pret                         1
Taux_endettement                    0.59
Défaut                                 Y
Nombre de credit historique            3
Name: 0, dtype: object

In [55]:
#Sélectionner la dernière colonne
df.iloc[-1]

Id_personne                        20
Age                                24
Nom                             Yemba
Prenom                         Elodie
Revenu                          10800
Type de domicile                 Pret
Travail                           CDD
Grade du pret                       B
Montant du prêt                  1750
Taux_interet                    10.99
Statut_du_pret                      1
Taux_endettement                 0.16
Défaut                              N
Nombre de credit historique         2
Name: 19, dtype: object

In [56]:
#Sélectionner les deux premières lignes et les deux première colonnes
df.iloc[:2,:2]

   Id_personne  Age
0            1   40
1            2   35

**3.4 Indexation avec loc (accéder aux éléments à partir des labels)**

In [59]:
#Création d'un index dans le dataframe df_etudiant
#df = df.set_index("Nom")
df
df.loc["Akono"]

Id_personne                            1
Age                                   40
Prenom                            Nathan
Revenu                             59000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          D
Montant du prêt                    35000
Taux_interet                       16.02
Statut_du_pret                         1
Taux_endettement                    0.59
Défaut                                 Y
Nombre de credit historique            3
Name: Akono, dtype: object

In [60]:
#Sélection de la ligne Mendong
df.loc["Mendong"]

Id_personne                            8
Age                                   24
Prenom                              Zibi
Revenu                             33000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          B
Montant du prêt                    35000
Taux_interet                       11.11
Statut_du_pret                         1
Taux_endettement                    0.44
Défaut                                 N
Nombre de credit historique            4
Name: Mendong, dtype: object

**4. Statistiques descriptives**

**4.1 Obtenir des statistiques de base(moyenne, médiane, écart-type)**

In [61]:
#Description des variables quantitatives
df.describe()

,Id_personne,Age,Revenu,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Nombre de credit historique
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,28.450000,82503.550000,25092.500000,12.253500,0.800000,0.352500,3.050000
std,5.91608,8.274724,105576.833252,15036.274341,3.899438,0.410391,0.154507,0.887041
min,1.00000,21.000000,9600.000000,1000.000000,7.140000,0.000000,0.060000,2.000000
25%,5.75000,23.000000,24750.000000,5250.000000,8.832500,1.000000,0.280000,2.000000
50%,10.50000,24.000000,64500.000000,35000.000000,11.125000,1.000000,0.345000,3.000000
75%,15.25000,32.500000,98290.000000,35000.000000,14.862500,1.000000,0.450000,4.000000
max,20.00000,50.000000,500000.000000,35000.000000,20.250000,1.000000,0.590000,4.000000

**4.2 Compter les valeurs uniques et les fréquences**

In [62]:
#Description des variables qualitatives
df.describe(include="object")

/var/folders/jj/mfrmmt4d5jlddtlxr2rq4n040000gn/T/ipykernel_63030/3082653242.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

       Prenom Type de domicile Travail Grade du pret Défaut
count      20               20      20            20     20
unique     18                3       3             6      2
top     Marie        Locataire     CDI             B      N
freq        2               10      11             6     18

In [66]:
#Compter les valeurs manquantes par variable
df.isnull().mean()

Id_personne                    0.0
Age                            0.0
Prenom                         0.0
Revenu                         0.0
Type de domicile               0.0
Travail                        0.0
Grade du pret                  0.0
Montant du prêt                0.0
Taux_interet                   0.0
Statut_du_pret                 0.0
Taux_endettement               0.0
Défaut                         0.0
Nombre de credit historique    0.0
dtype: float64

**5 Modifier les données**

**5.1 Suppression des lignes**

In [67]:
df.dropna(inplace=True)
df

,Id_personne,Age,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
Nom,,,,,,,,,,,,,
Akono,1,40,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
Akwa,2,35,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
Arnaud,3,25,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
Awa,4,23,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
Dubois,5,24,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
Durand,6,21,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
Ekounou,7,44,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
Mendong,8,24,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
Moussa,9,24,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
Mvog-ada,10,50,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
Mvogo,11,22,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
Neba,12,21,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
Ngo,13,34,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
Ngono,14,26,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
Omar,15,23,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
Petit,16,32,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
Richard,17,23,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
Tchana,18,31,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
Tchuente,19,23,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
Yemba,20,24,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

**5.2 Suppression d'une colonne**

In [68]:
#Supprimer une colone
df.drop("Revenu",axis=1)

,Id_personne,Age,Prenom,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
Nom,,,,,,,,,,,,
Akono,1,40,Nathan,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
Akwa,2,35,Aicha,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
Arnaud,3,25,Matin,Locataire,CDD,C,5500,12.87,1,0.57,N,3
Awa,4,23,Marie,Pret,CDI,C,35000,15.23,1,0.53,N,2
Dubois,5,24,Lachaise,Pret,CDI,C,35000,14.27,1,0.55,Y,4
Durand,6,21,Bertin,Locataire,CDD,A,2500,7.14,1,0.25,N,2
Ekounou,7,44,Eli,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
Mendong,8,24,Zibi,Locataire,CDI,B,35000,11.11,1,0.44,N,4
Moussa,9,24,Hamado,Locataire,CDI,A,35000,8.90,1,0.42,N,2
Mvog-ada,10,50,Bertin,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
Mvogo,11,22,Melanie,Locataire,CDD,B,35000,10.37,1,0.41,N,4
Neba,12,21,Charlène,Locataire,CDD,A,4500,8.63,1,0.45,N,2
Ngo,13,34,Stephanie,Pret,CDI,A,35000,7.90,1,0.37,N,2
Ngono,14,26,Marie,Pret,CDI,E,35000,18.39,1,0.32,N,4
Omar,15,23,Mohamed,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
Petit,16,32,Prince,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
Richard,17,23,Arnaud,Locataire,CDI,A,35000,7.90,0,0.29,N,4
Tchana,18,31,Albert,Locataire,CDD,F,35000,20.25,1,0.32,N,4
Tchuente,19,23,Isis,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
Yemba,20,24,Elodie,Pret,CDD,B,1750,10.99,1,0.16,N,2

**5.3 Création d'une nouvelle variable étant la multiplication de deux colonnes du tableau**

In [69]:
#Création d'une nouvelle variable comme étant la multiplication de deux colonnes du tableau
df["test"]=df["Montant du prêt"]*df["Taux_interet"]
df

,Id_personne,Age,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
Nom,,,,,,,,,,,,,,
Akono,1,40,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,560700.0
Akwa,2,35,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,11140.0
Arnaud,3,25,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,70785.0
Awa,4,23,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,533050.0
Dubois,5,24,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,499450.0
Durand,6,21,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,17850.0
Ekounou,7,44,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,434700.0
Mendong,8,24,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,388850.0
Moussa,9,24,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,311500.0
Mvog-ada,10,50,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,23584.0
Mvogo,11,22,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,362950.0
Neba,12,21,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,38835.0
Ngo,13,34,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,276500.0
Ngono,14,26,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,643650.0
Omar,15,23,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,276500.0
Petit,16,32,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,319500.0
Richard,17,23,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,276500.0
Tchana,18,31,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,708750.0
Tchuente,19,23,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,638750.0
Yemba,20,24,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,19232.5

**5.4 Mettre à jour une colonne**

In [70]:
#Mettre à jour avec une valeur pour toutes les lignes
df["test"]=100
df

,Id_personne,Age,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
Nom,,,,,,,,,,,,,,
Akono,1,40,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,100
Akwa,2,35,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,100
Arnaud,3,25,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
Awa,4,23,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,100
Dubois,5,24,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,100
Durand,6,21,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
Ekounou,7,44,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,100
Mendong,8,24,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,100
Moussa,9,24,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,100
Mvog-ada,10,50,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,100
Mvogo,11,22,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
Neba,12,21,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
Ngo,13,34,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,100
Ngono,14,26,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,100
Omar,15,23,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
Petit,16,32,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
Richard,17,23,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,100
Tchana,18,31,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
Tchuente,19,23,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
Yemba,20,24,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

**5.5 Mettre à jour une valeur**

In [71]:
#Mise à jour de la dernière colonne de la première ligne
df.iloc[0,-1]=100000
df

,Id_personne,Age,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
Nom,,,,,,,,,,,,,,
Akono,1,40,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,100000
Akwa,2,35,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,100
Arnaud,3,25,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
Awa,4,23,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,100
Dubois,5,24,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,100
Durand,6,21,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
Ekounou,7,44,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,100
Mendong,8,24,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,100
Moussa,9,24,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,100
Mvog-ada,10,50,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,100
Mvogo,11,22,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
Neba,12,21,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
Ngo,13,34,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,100
Ngono,14,26,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,100
Omar,15,23,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
Petit,16,32,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
Richard,17,23,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,100
Tchana,18,31,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
Tchuente,19,23,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
Yemba,20,24,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

**5.6 Mettre à jour des valeurs qui respectent des conditions**

In [74]:
#Modifier la valeur de la colonne d'une ligne en fonction d'une condition (remplacer D par F)
df.loc[df["Travail"]=="CDI","Travail"]="CDD"
df

,Id_personne,Age,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
Nom,,,,,,,,,,,,,,
Akono,1,40,Nathan,59000,Locataire,CDD,D,35000,16.02,1,0.59,Y,3,100000
Akwa,2,35,Aicha,70000,Propriétaire,CDD,B,1000,11.14,0,0.10,N,2,100
Arnaud,3,25,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
Awa,4,23,Marie,44000,Pret,CDD,C,35000,15.23,1,0.53,N,2,100
Dubois,5,24,Lachaise,54400,Pret,CDD,C,35000,14.27,1,0.55,Y,4,100
Durand,6,21,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
Ekounou,7,44,Eli,77100,Propriétaire,CDD,B,35000,12.42,1,0.45,N,3,100
Mendong,8,24,Zibi,33000,Locataire,CDD,B,35000,11.11,1,0.44,N,4,100
Moussa,9,24,Hamado,24000,Locataire,CDD,A,35000,8.90,1,0.42,N,2,100
Mvog-ada,10,50,Bertin,80000,Propriétaire,CDD,D,1600,14.74,1,0.16,N,3,100
Mvogo,11,22,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
Neba,12,21,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
Ngo,13,34,Stephanie,95000,Pret,CDD,A,35000,7.90,1,0.37,N,2,100
Ngono,14,26,Marie,108160,Pret,CDD,E,35000,18.39,1,0.32,N,4,100
Omar,15,23,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
Petit,16,32,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
Richard,17,23,Arnaud,120000,Locataire,CDD,A,35000,7.90,0,0.29,N,4,100
Tchana,18,31,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
Tchuente,19,23,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
Yemba,20,24,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

**6 Fusion et jointure de DataFrames**

In [76]:
#Création des datas frames exemple
data1 = {
    "ID":[1, 2, 3, 4],
    "Prénom": ["Alice", "Bob", "Charlie", "David"]
}
data2 = {
    "ID":[3, 4, 5, 6],
    "Ville":["Paris", "Lyon", "Marseille", "Toulouse"]
}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

#Effectuer une jointure interne(inner_join)
inner_join = df1.merge(df2, on="ID", how="inner")

#Effectuer une jointure externe(outer_join)
outer_join = df1.merge(df2, on="ID", how="outer")

#Effectuer une jointure gauche (left_join)
left_join = df1.merge(df2, on="ID", how="left")

#Effectuer une jointure droite (right_join)
right_join = df1.merge(df2, on="ID", how="right")

#Afficher les résultats
print("Inner join:")
print(inner_join)
print("\nOuter join")
print(outer_join)
print("\nLeft join")
print(left_join)
print("\nRight join")
print(right_join)

Inner join:
   ID   Prénom  Ville
0   3  Charlie  Paris
1   4    David   Lyon

Outer join
   ID   Prénom      Ville
0   1    Alice        NaN
1   2      Bob        NaN
2   3  Charlie      Paris
3   4    David       Lyon
4   5      NaN  Marseille
5   6      NaN   Toulouse

Left join
   ID   Prénom  Ville
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie  Paris
3   4    David   Lyon

Right join
   ID   Prénom      Ville
0   3  Charlie      Paris
1   4    David       Lyon
2   5      NaN  Marseille
3   6      NaN   Toulouse

**7 Enregistrer la base**

**7.1 Enregister en CSV**

In [ ]:
#Enregister en CSV
df.to_csv("test.csv)

**7.1 Enregister en CSV****7.2 Enregister en JSON**

In [ ]:
#Exporter en fichier json
df.to_json("test.json")